import Foundation

/// Curated list of common disposable/throwaway email domains for instant client-side
/// feedback during signup. This is intentionally a small subset (not the full
/// `disposable-email-domains` npm list, which has 30k+ entries) to keep the app binary
/// lean — `ridgits-api`'s `POST /api/auth/validate-signup` is the authoritative,
/// comprehensive check that runs before any Firebase Auth account is created, so a
/// domain missing from this list can't be used to bypass the block.
enum RidgitsDisposableEmail {
    static func isDisposable(_ email: String) -> Bool {
        guard let domain = email.split(separator: "@").last?.lowercased() else { return false }
        return domains.contains(String(domain))
    }

    static let domains: Set<String> = [
        "tempmail.com", "throwawaymail.com", "mailinator.com", "guerrillamail.com",
        "sharklasers.com", "yopmail.com", "getairmail.com", "10minutemail.com",
        "temp-mail.org", "trashmail.com", "trashmail.net", "dispostable.com",
        "fakeinbox.com", "mailnesia.com", "mintemail.com", "mytemp.email",
        "spamgourmet.com", "spambog.com", "spam4.me", "throwawayemailaddress.com",
        "tempinbox.com", "tempr.email", "temp-mail.io", "temp-mail.ru",
        "tempmailaddress.com", "tempmailo.com", "mailcatch.com", "mailinator.net",
        "mailinator2.com", "mailismagic.com", "maillinkin.com", "mailmetrash.com",
        "mailsac.com", "mail-temp.com", "mohmal.com", "moakt.com",
        "nada.email", "notsharingmy.info", "objectmail.com", "onewaymail.com",
        "1secmail.com", "1secmail.net", "1secmail.org", "20minutemail.com",
        "33mail.com", "anonbox.net", "anonymbox.com", "armyspy.com",
        "byom.de", "cuvox.de", "deadaddress.com", "despam.it",
        "devnullmail.com", "dodgeit.com", "dodgit.com", "dontreg.com",
        "dropmail.me", "e4ward.com", "einrot.com", "emailondeck.com",
        "emailtemporanea.com", "emailtemporar.ro", "emailthe.net", "emailtmp.com",
        "emailwarden.com", "ephemail.net", "fakemailgenerator.com", "fake-mail.ml",
        "fake-box.com", "fivemail.de", "flashmail.com", "fleckens.hu",
        "getnada.com", "grr.la", "guerrillamail.biz", "guerrillamail.de",
        "guerrillamail.info", "guerrillamail.net", "guerrillamail.org", "guerrillamailblock.com",
        "harakirimail.com", "hidemail.de", "hmamail.com", "hopemail.biz",
        "ieatspam.eu", "ieh-mail.de", "incognitomail.com", "incognitomail.org",
        "instant-mail.de", "irish2me.com", "jetable.com", "jetable.fr.nf",
        "jetable.net", "jetable.org", "jourrapide.com", "junk1e.com",
        "kasmail.com", "keepmymail.com", "killmail.com", "killmail.net",
        "kir.ch.tc", "klassmaster.com", "klzlk.com", "kurzepost.de",
        "letthemeatspam.com", "lifebyfood.com", "link2mail.net", "litedrop.com",
        "lookugly.com", "lortemail.dk", "lroid.com", "lukop.dk",
        "m4ilweb.info", "maboard.com", "mail-filter.com", "mail-owl.com",
        "mailbucket.org", "mailcat.biz", "mailde.de", "mailde.info",
        "maildrop.cc", "maileater.com", "mailexpire.com", "mailfa.tk",
        "mailforspam.com", "mailfreeonline.com", "mailfs.com", "mailguard.me",
        "mailin8r.com", "mailinater.com", "mailincubator.com", "mailmate.com",
        "mailms.com", "mailnull.com", "mailscrap.com", "mailseal.de",
        "mailshell.com", "mailsiphon.com", "mailslapping.com", "mailtemp.info",
        "mailtome.de", "mailtothis.com", "mailtrash.net", "mailtv.net",
        "mailtv.tv", "mailzilla.com", "mbx.cc", "mega.zik.dj",
        "meltmail.com", "mierdamail.com", "mintemail.net", "monumentmail.com",
        "msa.minsmail.com", "mt2009.com", "mt2014.com", "mycleaninbox.net",
        "mymail-in.net", "mypartyclip.de", "myphantomemail.com", "mytrashmail.com",
        "netmails.com", "netmails.net", "netzidiot.de", "neverbox.com",
        "no-spam.ws", "nobulk.com", "noclickemail.com", "nogmailspam.info",
        "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com", "nospam.ze.tc",
        "nospam4.us", "nospamfor.us", "nospammail.net", "nowhere.org",
        "nowmymail.com", "nurfuerspam.de", "objectmail.com", "obobbo.com",
        "onlatedotcom.info", "opayq.com", "ordinaryamerican.net", "otherinbox.com",
        "owlpic.com", "pancakemail.com", "pjjkp.com", "politikerclub.de",
        "poofy.org", "pookmail.com", "privacy.net", "privatdemail.net",
        "proxymail.eu", "punkass.com", "putthisinyourspamdatabase.com", "quickinbox.com",
        "rcpt.at", "reallymymail.com", "recode.me", "recursor.net",
        "regbypass.com", "rejectmail.com", "rmqkr.net", "royal.net",
        "rppkn.com", "rtrtr.com", "s0ny.net", "safe-mail.net",
        "safersignup.de", "safetymail.info", "safetypost.de", "sandelf.de",
        "saynotospams.com", "selfdestructingmail.com", "sendspamhere.com", "sharklasers.com",
        "shieldedmail.com", "shitmail.me", "shitware.nl", "shortmail.net",
        "sibmail.com", "skeefmail.com", "slaskpost.se", "slopsbox.com",
        "smashmail.de", "snakemail.com", "sneakemail.com", "sofimail.com",
        "sofort-mail.de", "sogetthis.com", "soodonims.com", "spam.la",
        "spam.su", "spamavert.com", "spambob.com", "spambob.net",
        "spambob.org", "spambog.de", "spambog.ru", "spambox.info",
        "spambox.us", "spamcannon.com", "spamcannon.net", "spamcero.com",
        "spamcon.org", "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
        "spamcowboy.org", "spamday.com", "spamex.com", "spamfree24.com",
        "spamfree24.de", "spamfree24.eu", "spamfree24.info", "spamfree24.net",
        "spamfree24.org", "spamherelots.com", "spamhereplease.com", "spamhole.com",
        "spamify.com", "spaminator.de", "spamkill.info", "spaml.com",
        "spaml.de", "spammotel.com", "spamobox.com", "spamoff.de",
        "spamsalad.in", "spamslicer.com", "spamspot.com", "spamthis.co.uk",
        "spamthisplease.com", "spamtrail.com", "speed.1s.fr", "supergreatmail.com",
        "supermailer.jp", "suremail.info", "teewars.org", "teleworm.com",
        "teleworm.us", "tempalias.com", "tempe-mail.com", "tempemail.biz",
        "tempemail.com", "tempemail.net", "tempinbox.co.uk", "tempmail2.com",
        "tempomail.fr", "temporarily.de", "temporarioemail.com.br", "temporaryemail.net",
        "temporaryemail.us", "temporaryforwarding.com", "temporaryinbox.com", "thankyou2010.com",
        "thisisnotmyrealemail.com", "throam.com", "throwawayemailaddresses.com", "tilien.com",
        "tittbit.in", "toiea.com", "tradermail.info", "trash-amil.com",
        "trash-mail.at", "trash-mail.com", "trash-mail.de", "trash2009.com",
        "trashdevil.com", "trashemail.de", "trashinbox.com", "trashmail.at",
        "trashmail.de", "trashmail.me", "trashmail.ws", "trashmailer.com",
        "trashymail.com", "trashymail.net", "trbvm.com", "trickmail.net",
        "trillianpro.com", "tryalert.com", "turual.com", "twinmail.de",
        "tyldd.com", "uggsrock.com", "umail.net", "uroid.com",
        "us.af", "venompen.com", "veryrealemail.com", "viditag.com",
        "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org", "vpn.st",
        "vsimcard.com", "vubby.com", "wasteland.rfc822.org", "webemail.me",
        "weg-werf-email.de", "wegwerf-email.de", "wegwerf-emails.de", "wegwerfadresse.de",
        "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.de", "wegwerfmail.info",
        "wegwerfmail.net", "wegwerfmail.org", "wetrainbayarea.com", "wetrainbayarea.org",
        "wh4f.org", "whyspam.me", "willselfdestruct.com", "winemaven.info",
        "wronghead.com", "wuzup.net", "wuzupmail.net", "xoxy.net",
        "yep.it", "yogamaven.com", "yopmail.fr", "yopmail.net",
        "ypmail.webarnak.fr.eu.org", "yuurok.com", "zehnminuten.de", "zehnminutenmail.de",
        "zippymail.info", "zoemail.net", "zomg.info",
    ]
}
